const BookingData = [
  {
    id: 1,
    doctor_id: "dao",
    patient_id: "benh nhan 1",
    time_id: 1,
    clinic_id: 1,
    description: "sdasd",
    status: "Pending",
    createdAt: "2025-08-15",
  },
  {
    id: 2,
    patient_id: "benh nhan 2",
    time_id: 1,
    clinic_id: 2,
    doctor_id: "daoVuVan",
    description: "sdasd",
    status: "Pending",
    createdAt: "2025-09-12",
  },
  {
    id: 3,
    patient_id: "benh nhan 3",
    time_id: 1,
    clinic_id: 3,
    doctor_id: "VuVanDao",
    description: "sdasd",
    status: "Pending",
    createdAt: "2025-03-03",
  },
  {
    id: 4,
    patient_id: "benh nhan 4",
    time_id: 1,
    clinic_id: 4,
    doctor_id: "Daohehehe",
    description: "sdasd",
    status: "Pending",
    createdAt: "2025-01-01",
  },
  {
    id: 5,
    patient_id: "benh nhan 5",
    time_id: 1,
    clinic_id: 5,
    doctor_id: "daoVipPro",
    description: "sdasd",
    status: "Pending",
    createdAt: "2025-08-15",
  },
  {
    id: 6,
    patient_id: "benh nhan 6",
    time_id: 1,
    clinic_id: 6,
    doctor_id: "VanDao",
    description: "sdasd",
    status: "Done",
    createdAt: "2025-08-15",
  },
  {
    id: 7,
    patient_id: "benh nhan 7",
    time_id: 1,
    clinic_id: 7,
    doctor_id: "Daohihihi",
    description: "sdasd",
    status: "Done",
    createdAt: "2025-08-15",
  },
  {
    id: 8,
    patient_id: "benh nhan 8",
    time_id: 1,
    clinic_id: 8,
    doctor_id: "dao",
    description: "sdasd",
    status: "Done",
    createdAt: "2025-08-15",
  },
];
export default BookingData;
