spring.application.name=Booking-care
spring.jpa.hibernate.ddl-auto=update

# TỰ TẠO DB nếu chưa có:
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/booking_care?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



###
# config pagination
# start page = 1
spring.data.web.pageable.one-indexed-parameters=true
###
#

###
# config jwt
booking-care.jwt.base-secret = TRrx3ZoD9xgevlM73MU8/ay9VO+8RJ7NjvFh5Ab0xoTsKzuPYwCOKDZugGYsVxroYRfP94DH6jBxBhFyBPaQQQ==
# 100 day
booking-care.jwt.access-token-validity-in-seconds = 86400
booking-care.jwt.refresh-token-validity-in-seconds = 864000


###
# config cloudinary
booking-care.cloudinary.cloud_name=dcoejntp5
booking-care.cloudinary.api_key=133775389187948
booking-care.cloudinary.api_secret=Azgfz0fls5xec_WAbr4EpxyWkTY
###
#

###
# config spring mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bookingcare67@gmail.com
#app password
spring.mail.password=mxvgeeylncghzorz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
###
#

###
# config expiry time otp
spring.email.otp.expiry-time-seconds = 60
###
#

